version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbit-compose
    hostname: my-rabbit-hostname
    ports:
      - "5672:5672"
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit_disk_free_limit 200000000

volumes:
  rabbitmq_data: 
    driver: local
